version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 12
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run lt
      - npm run test
  build:
    commands:
     - |
        if [ "$Validate" = "true" ]; then
          npm publish --dry-run  || { echo 'publish failed'; exit 1; }
        else
          # check if commit message matches a version bump e.g. 1.7.437
          regexp='^\d+\.\d+\.\d+$'
          message=`git log --oneline --format=%B -n 1 $CODEBUILD_RESOLVED_SOURCE_VERSION | head -n 1` || { echo 'get commit message failed'; exit 1; }
          match=`node -e "console.log(/$regexp/.test(\"$message\".trim()))"` || { echo 'parse commit failed'; exit 1; } # bash regex didn't work here: "[[: not found"

          aws s3 cp $S3HomePath ~ --recursive
          token=`cat ~/.github`

          if [ "$match" = "false" ]; then
            git clone --single-branch --branch master https://$token@github.com/mutual-of-enumclaw/orchestrator.git
            cd orchestrator || { echo 'orchestrator not found' ; exit 1; }
            npm version patch || { echo 'npm patch failed' ; exit 1; }
            git push https://$token@github.com/mutual-of-enumclaw/orchestrator.git master || { echo 'git push failed' ; exit 1; }
          else
            npm run buildPublish || { echo 'publish failed'; exit 1; }
            git clone --single-branch --branch master https://$token@github.com/mutual-of-enumclaw/nucleus-lib-services.git
            cd nucleus-lib-services || { echo 'nucleus-lib-services not found' ; exit 1; }
            npm i @moe-tech/orchestrator@latest
            git commit -am "autoupdate orchestrator" || { echo 'commit failed' ; exit 1; }
            git push https://$token@github.com/mutual-of-enumclaw/nucleus-lib-services.git master || { echo 'git push failed' ; exit 1; }
          fi
        fi
      