version=0.1
[default.deploy.parameters]
base_stack = "nucleus-orchestrator-core"
environment = "snd"
s3_bucket = "moe-deployment-snd"
s3_prefix = "nucleus/snd/nucleus-orchestrator-core"
region = "us-west-2"
confirm_changeset = "false"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parm_layer = "true"
env_aware = "true"