Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs12.x
    CodeUri: "."
    MemorySize: 128
    Timeout: 30
    Environment:
      Variables:
        orchestratorStatusTable:
          Fn::ImportValue: !Sub ${OrchestratorStack}-status-name
    Layers:
      - !Ref OrchestratorLayerArn

Parameters:
  OrchestratorStack:
    Type: String
    Description: The name of the orchestrator stack
  OrchestratorLayerArn:
    Type: String

Resources:
  prePostPlugin:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-prePostPlugin
      Handler: plugin.plugin
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: prePostPlugin
      Environment:
        Variables:
          stage: pre-Activity
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - Fn::ImportValue: !Sub ${OrchestratorStack}-status-arn
      Events:
        Topic1:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue: !Sub ${OrchestratorStack}-Step2-pre-processing
            Region: !Ref AWS::Region
        
  prePostPlugin:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-prePostPlugin
      Handler: plugin.plugin
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: prePostPlugin
      Environment:
        Variables:
          stage: post-Activity
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - Fn::ImportValue: !Sub ${OrchestratorStack}-status-arn
      Events:
        Topic2:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue: !Sub ${OrchestratorStack}-Step2-post-processing
            Region: !Ref AWS::Region