Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs12.x
    CodeUri: "."
    MemorySize: 128
    Timeout: 30
    Environment:
      Variables:
        OrchestratorConfig: !Ref OrchestratorConfig
    Layers:
      - !Ref OrchestratorLayerArn

Parameters:
  OrchestratorStack:
    Type: String
    Description: The name of the orchestrator stack
  OrchestratorLayerArn:
    Type: AWS::SSM::Parameter<string>
    Default: /<EnvironmentName>/orchestrator/stacks/<StackName>/layer
  OrchestratorConfig:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/orchestrator/stacks/<StackName>/config

Resources:
  prePlugin:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-prePlugin
      Handler: plugin.plugin
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: prePostPlugin
      Environment:
        Variables:
          stage: pre-Activity
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource:
                - Fn::ImportValue: !Sub ${OrchestratorStack}-status-arn
      Events:
        Topic1:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue: !Sub ${OrchestratorStack}-Step2-pre-processing
            Region: !Ref AWS::Region
        
  postPlugin:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-postPlugin
      Handler: plugin.plugin
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: prePostPlugin
      Environment:
        Variables:
          stage: post-Activity
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource:
                - Fn::ImportValue: !Sub ${OrchestratorStack}-status-arn
      Events:
        Topic2:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue: !Sub ${OrchestratorStack}-Step2-post-processing
            Region: !Ref AWS::Region